services:
  - type: web
    name: flask-backend
    env: docker
    repo: https://github.com/Bhagyapulla/my-app
    branch: main
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
      - key: SECRET_KEY
        value: your-secret-key
      - key: POTRACE_PATH
        value: /usr/bin/potrace
  - type: static
    name: react-frontend
    repo: https://github.com/Bhagyapulla/my-app
    branch: main
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/build
    plan: free
    region: oregon
    envVars:
      - key: REACT_APP_API_URL
        value: https://flask-backend.onrender.com